<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '绿茶',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '六安瓜片',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '六安瓜片',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '西湖龙井',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '2',
    'name' => '西湖龙井',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '太平猴魁',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => '太平猴魁',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '黄山毛峰',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '黄山毛峰',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '红酒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '49',
    'name' => '红酒',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '49',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '50',
    'name' => '红葡萄酒',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '白葡萄酒',
    'measure_unit' => '',
    'parent_id' => '49',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '51',
    'name' => '白葡萄酒',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '黑茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '30',
    'name' => '黑茶',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '普 洱 茶',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '31',
    'name' => '普 洱 茶',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '乌龙茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '15',
    'name' => '乌龙茶',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '大 红 袍',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '17',
    'name' => '大 红 袍',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '其他乌龙茶',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '其他乌龙茶',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '台湾乌龙',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '台湾乌龙',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '水　　仙',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '水　　仙',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '铁 观 音',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '16',
    'name' => '铁 观 音',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '肉　　桂',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '肉　　桂',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '白茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '白茶',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '白 牡 丹',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '27',
    'name' => '白 牡 丹',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '寿　　眉',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '寿　　眉',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '新工艺白茶',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '29',
    'name' => '新工艺白茶',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '白毫银针',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '白毫银针',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '红茶',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '其他红茶',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '其他红茶',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '白琳工夫',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '白琳工夫',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '祁门红茶',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => '祁门红茶',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '坦洋工夫',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '12',
    'name' => '坦洋工夫',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '滇红工夫',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '滇红工夫',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '金骏眉',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => '金骏眉',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '政和工夫',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '政和工夫',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '正山小种',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '7',
    'name' => '正山小种',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '花茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '22',
    'name' => '花茶',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '台湾冷泡茶',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '24',
    'name' => '台湾冷泡茶',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '茉莉花茶',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '23',
    'name' => '茉莉花茶',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '茶具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '32',
    'name' => '茶具',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '紫 砂 壶',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '紫 砂 壶',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '茶　　盘',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '茶　　盘',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '茶壶茶杯',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '茶壶茶杯',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '饰品配件',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '饰品配件',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '工夫茶具',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '35',
    'name' => '工夫茶具',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '电子茶具',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '电子茶具',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '特色工艺礼品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '42',
    'name' => '特色工艺礼品',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '香　　炉',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '香　　炉',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '佛　　像',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '佛　　像',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '插 香 器',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '插 香 器',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '线香香粉',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '线香香粉',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '漆 线 雕',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => '漆 线 雕',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '沉　　香',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '沉　　香',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '特色茶产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '39',
    'name' => '特色茶产品',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '茶　　枕',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '40',
    'name' => '茶　　枕',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '绞 股 蓝',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => '绞 股 蓝',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '功效',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '52',
    'name' => '功效',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '减肥瘦身',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => '减肥瘦身',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '提神消疲',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '提神消疲',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '防 辐 射',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '防 辐 射',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '调理肠胃',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '调理肠胃',
  ),
);
?>